// The data the page is built from, and the small facts about it.
//
// `map.json` is generated by build/build.py out of the game itself: the node
// positions the game's own map screen uses, the zone names in the eleven
// languages it ships, and the drop tables the tracker reads from the same
// executable. Nothing here is typed by hand.

export const asset = (path) => import.meta.env.BASE_URL + path;

export async function load() {
  const res = await fetch(asset('data/map.json'));
  if (!res.ok) throw new Error(`map.json: ${res.status} ${res.statusText}`);
  return res.json();
}

/** Which sprite a marker is drawn with. */
export const ART = { zone: 'node', dungeon: 'dungeon', town: 'town', cabin: 'town' };

/** What to call it in the panel's subtitle. */
export const KIND = { zone: 'zone', dungeon: 'boss dungeon', town: 'town', cabin: 'cabin' };

export const nameOf = (node, lang) => node.name[lang] || node.name.en || node.room;

/**
 * The tables hold names folded to lower case; the game shows them capitalised.
 *
 * Not after an apostrophe: nearly every name in this game is possessive, and
 * capitalising there gives "Pagan God'S Blasphemy" and "Nikita'S Kj-33".
 */
export const titleCase = (s) => s.replace(/(^|[\s([-])\p{Ll}/gu, (c) => c.toUpperCase());

/** "1 in 46k" — a drop rate is a denominator, and a bare 46750 says nothing. */
export function odds(n) {
  if (!n || n <= 0) return '';
  if (n >= 1_000_000) return `1 in ${(n / 1_000_000).toFixed(n >= 10_000_000 ? 0 : 1)}M`;
  if (n >= 1000) return `1 in ${Math.round(n / 1000)}k`;
  return `1 in ${n}`;
}
