// The data the page is built from, and the small facts about it.
//
// `map.json` is generated by build/build.py out of the game itself: the node
// positions the game's own map screen uses, the zone names in the eleven
// languages it ships, and the drop tables the tracker reads from the same
// executable. Nothing here is typed by hand.

/**
 * A file this page needs, stamped so a stale one is never used.
 *
 * The data and the art sit in `public/`, which means their names never change
 * from one build to the next — and the boxes in `map.json` are coordinates into
 * a particular sheet. Publish a new sheet and a browser holding the old one
 * cuts every icon in the wrong place: entries slide, half of one shows, the
 * shelf looks scrambled. That happened.
 *
 * The stamp is a hash of everything in `public/data` and `public/img`, so it
 * changes when they do and not otherwise — a deploy that touches only the code
 * leaves the megabyte of art in the reader's cache where it is.
 */
export const asset = (path) => `${import.meta.env.BASE_URL}${path}?v=${__STAMP__}`;

export async function load() {
  const res = await fetch(asset('data/map.json'));
  if (!res.ok) throw new Error(`map.json: ${res.status} ${res.statusText}`);
  return res.json();
}

/** Which sprite a marker is drawn with. */
export const ART = {
  zone: 'node', dungeon: 'dungeon', dungeons: 'dungeonmark', town: 'town', cabin: 'town',
};

/** What to call it in the panel's subtitle. */
export const KIND = {
  zone: 'zone', dungeon: 'boss dungeon', dungeons: 'dungeon', town: 'town', cabin: 'cabin',
};

export const nameOf = (node, lang) => node.name[lang] || node.name.en || node.room;

/**
 * An item or a source as the game names it, in the reader's language.
 *
 * The drop tables key everything by a lower-case English name, which is what
 * the page has in hand; the eleven names ride on the record beside it. Falling
 * back to the key title-cased is what this did for every language before the
 * game's own names were carried, and it is still the answer for the six sources
 * the game has no name for.
 */
export const called = (rec, key, lang) => rec?.names?.[lang] || titleCase(key);

/**
 * The tables hold names folded to lower case; the game shows them capitalised.
 *
 * Not after an apostrophe: nearly every name in this game is possessive, and
 * capitalising there gives "Pagan God'S Blasphemy" and "Nikita'S Kj-33".
 */
export const titleCase = (s) => s.replace(/(^|[\s([-])\p{Ll}/gu, (c) => c.toUpperCase());

/** "1 in 46k" — a drop rate is a denominator, and a bare 46750 says nothing. */
export function odds(n) {
  if (!n || n <= 0) return '';
  if (n >= 1_000_000) return `1 in ${(n / 1_000_000).toFixed(n >= 10_000_000 ? 0 : 1)}M`;
  if (n >= 1000) return `1 in ${Math.round(n / 1000)}k`;
  return `1 in ${n}`;
}

/**
 * What the address bar is holding, so a page can be reloaded or sent to
 * somebody and open on the same thing.
 *
 * `replaceState` rather than `pushState`: opening one item after another would
 * otherwise stack up a history a reader has to walk back through, and the back
 * button should leave the page rather than step through what was read on it.
 */
export function recall(key) {
  try {
    return new URL(location.href).searchParams.get(key);
  } catch {
    return null;
  }
}

export function remember(pairs) {
  try {
    const url = new URL(location.href);
    for (const [key, value] of Object.entries(pairs)) {
      if (value == null || value === '') url.searchParams.delete(key);
      else url.searchParams.set(key, String(value));
    }
    history.replaceState(null, '', url);
  } catch {
    /* a browser that will not have it still shows the page */
  }
}
